export const ADMIN_INSIGHT_TYPES = {
  ORG_SCORE_OVERVIEW: "ORG_SCORE_OVERVIEW",
  COACHING_EFFECTIVENESS: "COACHING_EFFECTIVENESS",
  RISK_DISTRIBUTION: "RISK_DISTRIBUTION",
  TOP_IMPROVEMENTS: "TOP_IMPROVEMENTS",
};
