// Central list of all observable workspace events

export const EVENT_TYPES = {
  // Projects
  PROJECT_CREATED: "PROJECT_CREATED",
  PROJECT_UPDATED: "PROJECT_UPDATED",
  PROJECT_ARCHIVED: "PROJECT_ARCHIVED",

  // Tasks
  TASK_CREATED: "TASK_CREATED",
  TASK_UPDATED: "TASK_UPDATED",
  TASK_ASSIGNED: "TASK_ASSIGNED",
  TASK_STATUS_CHANGED: "TASK_STATUS_CHANGED",
  TASK_PROGRESS_UPDATED: "TASK_PROGRESS_UPDATED",
  TASK_DELETED: "TASK_DELETED",

  // Subtasks
  SUBTASK_CREATED: "SUBTASK_CREATED",
  SUBTASK_UPDATED: "SUBTASK_UPDATED",
  SUBTASK_DELETED: "SUBTASK_DELETED",

  // Attendance / Presence (future)
  USER_SIGNED_IN: "USER_SIGNED_IN",
  USER_SIGNED_OUT: "USER_SIGNED_OUT",
  USER_STATUS_CHANGED: "USER_STATUS_CHANGED",

// External Integrations (Observed Activity)
INTEGRATION_ACTIVITY_OBSERVED: "INTEGRATION_ACTIVITY_OBSERVED",
INTEGRATION_TASK_COMPLETED: "INTEGRATION_TASK_COMPLETED",
INTEGRATION_TASK_UPDATED: "INTEGRATION_TASK_UPDATED", };
